services:
  - docker

before_install: 
  - docker build -t hazartilirot/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hazartilirot/react-test npm run test -- --coverage

after_success: 
  - docker build -t hazartilirot/fibonacci-client ./client
  - docker build -t hazartilirot/fibonacci-nginx ./nginx
  - docker build -t hazartilirot/fibonacci-server ./server
  - docker build -t hazartilirot/fibonacci-worker ./worker
    
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push hazartilirot/fibonacci-client
  - docker push hazartilirot/fibonacci-nginx
  - docker push hazartilirot/fibonacci-server
  - docker push hazartilirot/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-container-fibonacci
  env: Multicontainerfibonacci-env
  bucket_name: elasticbeanstalk-eu-central-1-035766875271
  bucket_path: multi-container-fibonacci
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY