version: "3.9"

services:
  
  client:
    image: hazartilirot/fibonacci-client
    
  api:
    image: hazartilirot/fibonacci-server
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
    
  worker:
    image: hazartilirot/fibonacci-worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    
  nginx:
    image: hazartilirot/fibonacci-nginx
    ports:
      - "80:80"
    depends_on:
      - api
      - client